name: Deploy2 to Azure

on:
  workflow_dispatch:
env:
  MI_VARIABLE_GLOBAL: ${{ vars.MI_VARIABLE_GLOBAL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MI_VARIABLE_GLOBAL
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'action'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
