name: Ejemplo con Expresiones Lógicas

on:
  push:
    branches:
      - main
      - develop

env:
  ENVIRONMENT: 'producción'

jobs:
  evaluar-condiciones:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' # Usando operadores lógicos

    steps:
      - name: Imprimir información básica
        run: echo "Ref actual ${{ github.ref }}"

      - name: Usar formato dinámico
        run: echo "${{ format('El actor {0} ha hecho push en la rama {1}', github.actor, github.ref_name) }}"

      - name: Evaluar valor de entorno
        if: env.ENVIRONMENT == 'producción'
        run: echo "El entorno es producción"

      - name: Convertir a JSON
        run: echo '${{ toJSON(github) }}'
