name: primer-action
run-name: primer action
on:
  push:
    branches:
      - main
    schedules:
      - cron: '0 8 * * 1-5' # Cada día a la medianoche  


jobs:
  holamundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable de entorno
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python holamundo.py