name: Estrategia de Pruebas
on: [push]

jobs:
  pruebas:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest

      - name: Mostrar sistema operativo
        run: | 
          echo "SO: ${{ matrix.os }}"

      - name: Mostrar versión de Python
        run: |
          echo "Versión de Python: ${{ matrix.python-version }}"
